<?php

use Illuminate\Database\Seeder;
use App\Models\Market;

class MarketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $markets = [
			['id' => '1',
			'user_id' => '1',			
			'name' => 'Lascassas Farmers Market',
			'comments' => 'Saturdays, Year round, 8 a.m. to Noon',
			'website' => 'http://www.lascassasfarmersmarket.com',
			'image' => 'https://images.unsplash.com/photo-1567306295427-94503f8300d7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => '7684 Barlow Ln',
			'city' => 'Lascassas',
			'state' => 'TN',
			'zipcode' => '37085',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '2',
			'user_id' => '1',
			'name' => 'Main Street Saturday Market',
			'comments' => 'Saturdays, 8 a.m. to Noon, June to September. Note this example has no real address.',
			'website' => 'Facebook',
			'image' => 'https://images.unsplash.com/photo-1514425263458-109317cc1321?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => 'Historic Downtown Square',
			'city' => '',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '3',
			'user_id' => '1',
			'name' => 'Rutherford County Farmers Market',
			'comments' => 'Producer-only market featuring tons of great locally made items. Tuesdays and Fridays, 7 a.m. to Noon, Market runs 2nd Friday in May through the end of October.',
			'website' => 'extension.tennessee.edu/Rutherford',
			'image' => 'https://images.unsplash.com/photo-1559855604-f11cd5d385eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => 'Lane Agri-Park Community Center, John R Rice Blvd',
			'city' => 'Murfreesboro',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '4',
			'user_id' => '1',
			'name' => 'Smyrna Depot Farmers Market',
			'comments' => 'Pick TN Products Favorite Market in 2019. Saturdays, 8 a.m. to noon, May 23 to October',
			'website' => 'carpeartista.com/farmers-market',
			'image' => 'https://images.unsplash.com/photo-1565032152942-0258a20b0c1f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => 'Historic Train Depot on Front Street',
			'city' => 'Smyrna',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '5',
			'user_id' => '1',
			'name' => 'Stones River Market',
			'comments' => '***Need to checl. Really close business model. Year round, Deliveries on Wednesday. Online.',
			'website' => 'stonesriver.locallygrown.net',
			'image' => 'https://images.unsplash.com/photo-1533167751327-4091607cecc5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => '301. N. Spring St.',
			'city' => 'Murfreesboro',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '6',
			'user_id' => '1',
			'name' => 'Batch and Bushel Farmers Market',
			'comments' => 'Thursdays, 4 to 7 p.m., May to October',
			'website' => 'batchandbushel.com',
			'image' => 'https://images.unsplash.com/photo-1533264533981-8aead62802fd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => 'Wilson County Fairgrounds',
			'city' => '',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '7',
			'user_id' => '1',
			'name' => 'Nolensville Farmers Market',
			'comments' => 'Producer-only market featuring tons of great locally made items. Saturdays, 8 a.m. to Noon, May to October',
			'website' => 'nolensvillefarmersmarket.com',
			'image' => 'https://images.unsplash.com/photo-1546776473-c5f38714e230?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => '7248 Nolensville Rd',
			'city' => 'Nolensville',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '8',
			'user_id' => '1',
			'name' => 'Short Mountain Cultures',
			'comments' => 'Tuesday–Friday, 10am–6 p.m.; Saturday, 10 a.m.-4 p.m.; Sunday, noon-4 p.m.',
			'website' => 'shortmountaincultures.com',
			'image' => 'https://images.unsplash.com/photo-1567610990536-870948305215?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => '1424 John Bragg Highway',
			'city' => 'Woodbury',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '9',
			'user_id' => '1',
			'name' => 'Thompsons Station Farmers Market',
			'comments' => 'Small town market featuring locally made/grown items! Thursdays, 4-7 p.m.',
			'website' => 'tsfarmersmarket.org',
			'image' => 'https://images.unsplash.com/photo-1510442437064-523bec01a056?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => '1513 Thompson Station Rd W',
			'city' => 'Thompsons Station',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved' => 'N'],

			['id' => '10',
			'user_id' => '1',
			'name' => 'Tullahoma Farmers Market',
			'comments' => 'Only locally made or grown items allowed. No resale. Monday evenings, 3 p.m. to 7 p.m. (as a drive thru at this time), April thru October.',
			'website' => 'Facebook',
			'image' => 'https://images.unsplash.com/photo-1566273873209-5ceccc0d1514?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60',
			'address' => '201 NW Atlantic St.',
			'city' => 'Tullahoma',
			'state' => 'TN',
			'zipcode' => '',
			'latitude' => '',
			'longitude' => '',
			'start' => '8/1/2020',
			'end' => '8/1/2020',
			'approved'=> 'N']
		];
		
		foreach ($markets as $market) {
			Market::create(array(
				'id'  => $market['id'],
				'user_id' => $market['user_id'],
				'name' => $market['name'],
				'comments' => $market['comments'],
				'website' => $market['website'],
				'image' => $market['image'],
				'address' => $market['address'],
				'city' => $market['city'],
				'state' => $market['state'],
				'zipcode' => $market['zipcode'],
				'latitude' => $market['latitude'],
				'longitude' => $market['longitude'],
				'start' => $market['start'],
				'end' => $market['end'],
				'approved' => $market['approved']
			));
		}
    }
}
